---
# ============================================
# INSTALLATION TASKS
# ============================================
- name: Include task to check requirements in the nodes
  import_tasks: check_nodes.yml

- name: Include Task for swap config
  import_tasks: config_nodes_swap.yml

- name: Include kubeadmin installation tasks for kubeadm, kubelet, and kubectl
  import_tasks: installing_tools_kkk.yml

- name: Include kubeadmin installation tasks for container runtime
  import_tasks: installing_tools_cr.yml