---
# ============================================
# UNINSTALLATION TASKS
# ============================================
- name: Include kubeadmin uninstallation tasks for container runtime
  import_tasks: uninstalling_tools_cr.yml

- name: Include kubeadmin uninstallation tasks for kubeadm, kubelet, and kubectl
  import_tasks: uninstalling_tools_kkk.yml

- name: Include Task to restore swap (optional)
  import_tasks: restore_swap.yml